/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'couriers': RouteRecordInfo<'couriers', '/couriers', Record<never, never>, Record<never, never>>,
    'couriers-dashboard': RouteRecordInfo<'couriers-dashboard', '/couriers/dashboard', Record<never, never>, Record<never, never>>,
    'inventory-categories': RouteRecordInfo<'inventory-categories', '/inventory/categories', Record<never, never>, Record<never, never>>,
    'inventory-products': RouteRecordInfo<'inventory-products', '/inventory/products', Record<never, never>, Record<never, never>>,
    'laporan': RouteRecordInfo<'laporan', '/laporan', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'orders': RouteRecordInfo<'orders', '/orders', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'shipping-rates': RouteRecordInfo<'shipping-rates', '/shipping-rates', Record<never, never>, Record<never, never>>,
  }
}
